#!/usr/bin/env bash
set -euo pipefail
BASE="$(cd "$(dirname "$0")/.." && pwd)"
python3 "$BASE/src/niche_scoring.py"
python3 "$BASE/src/topic_planner.py"
python3 "$BASE/src/buyer_intent_expander_round2.py"
python3 "$BASE/src/topic_planner.py"
python3 "$BASE/src/markdown_generator.py"
python3 "$BASE/src/content_enricher.py"
python3 "$BASE/src/trust_page_builder.py"
python3 "$BASE/src/trust_tone_rewriter.py"
python3 "$BASE/src/homepage_curator.py"
python3 "$BASE/src/homepage_conversion_enhancer.py"
python3 "$BASE/src/content_refiner.py"
python3 "$BASE/src/money_page_rewriter.py"
python3 "$BASE/src/manual_quality_pass.py"
python3 "$BASE/src/content_cards_enhancer.py"
python3 "$BASE/src/product_record_enhancer.py"
python3 "$BASE/src/product_card_visual_enhancer.py"
python3 "$BASE/src/product_verdict_enhancer.py"
python3 "$BASE/src/comparison_block_enhancer.py"
python3 "$BASE/src/comparison_matrix_enhancer.py"
python3 "$BASE/src/internal_link_block_enhancer.py"
python3 "$BASE/src/site_navigation_enhancer.py"
python3 "$BASE/src/affiliate_link_injector.py"
python3 "$BASE/src/hybrid_monetization_enhancer.py"
python3 "$BASE/src/hierarchy_cleanup_enhancer.py"
python3 "$BASE/src/help_flow_enhancer.py"
python3 "$BASE/src/final_cleanup_enhancer.py"
python3 "$BASE/src/site_index_builder.py"
python3 "$BASE/src/monitoring_registry.py"
python3 "$BASE/src/review_queue_builder.py"
python3 "$BASE/src/html_builder.py"
python3 "$BASE/src/schema_injector.py"
python3 "$BASE/src/outbound_click_tracking_enhancer.py"
python3 "$BASE/src/metadata_builder.py"
python3 "$BASE/src/sitemap_builder.py"
echo "Build complete"
